baseURL = "https://jacob.vercel.app/"
languageCode = "en-us"
title = "Jacob"
theme = "jacob"
copyright = "Copyright © 2021 Powered by ❤ by "
metaDataFormat = "yaml"

[menu]
# [[menu.main]]
# URL = "/"
# name = "Home"
# weight = 1

[[menu.main]]
URL = "/work/"
name = "Work"
weight = 2

[[menu.main]]
URL = "/about/"
name = "About"
weight = 3

[[menu.main]]
URL = "/contact/"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "img/logo-emptyarea.svg"
logo_light = "img/logo-light.svg"

email = "taoguangc@gmail.com"
address = "125/A, CA Commercial Area, California, USA"
author = "Jeffrey Qian"
description = "This is meta description"
google_analytics_id = "" # Your ID


imageWidths = [1500, 900, 600]

[module]
[[module.mounts]]
source = "static/images"
target = "assets/images"